### ISSUE TITLE
Support for image styles with s3fs module

### ISSUE THREAD

**Issue by iBobik** [drupal-docker/nginx#15]
Module [S3 File System](https://www.drupal.org/project/s3fs) adds stream wrapper for using AWS S3 as a files storage in Drupal. It also integrates image styles, but it uses different path for first load - /s3/files/styles/...

This config for Nginx solves it (from s3fs README):
```
location ~ (^/s3/files/styles/|^/sites/.*/files/imagecache/|^/sites/default/themes/.*/includes/fonts/|^/sites/.*/files/styles/) {
        expires max;
        try_files $uri @rewrite;
    }
```

Can I send PR with this modification (it has no effect for users without s3fs)?

**Comment by zaporylie** [comment]
Hi Jan. First of all - I am so glad you spent some time to create an issue/contribute to this project. This project (drupal-docker) was always meant to be maintained by community, so all issues and PRs are always welcomed.

s3fs case is special. I am open to discuss it more but I am not happy with code snippet you have pasted above. First of all it does more than just react to /s3* prefixed path (also re-implement rewrite rules for /sites/.* files and fonts in theme?!) . Second it is oriented on only one implementation of s3 integration (s3fs over amazons3) which IMHO is not entirely fair.

This is why I would opt for having drupal.conf overwrite on per-project basis rather than keep it here for everyone. However I believe we could try to make nginx *.conf structure more flexible and pluggable so you could easily add s3fs.conf rather than overriding entire drupal.conf configuration.

Closing this issue but please do not hesitate to open it back if you disagree or want to discuss it more.

**Comment by iBobik** [comment]
Ok. This kind of decision is needed :-)
